characterise_results('material_study.txt', 2);
close('all');
characterise_results('support_height_study.txt');
close('all');
characterise_results('beam_length_study.txt');
close('all');
characterise_results('material_study.txt');
close('all');
analyse_prestress('prestress_study.txt');
characterise_results('prestressed_characteristic_study.txt');
close('all');
analyse_timestep('timestep_study.txt');
close('all');